const roles={NZP:["Constable","Senior Constable","Sergeant","Senior Sergeant","Inspector"],FENZ:["Firefighter","Senior Firefighter","Station Officer"],"St John":["EMT","Paramedic","Clinical Lead"],DOT:["Traffic Officer","Senior Traffic Officer","Supervisor"],Staff:["Moderator","Senior Moderator","Supervisor","Administrator","Management"]};
const units=[["NZP 2A-21","NZP","Ford Explorer","NZP-201",31,43,"🚓"],["NZP 4A-17","NZP","BMW M5","NZP-417",60,29,"🚓"],["FENZ 12","FENZ","Scania P-Series","FENZ-12",74,62,"🚒"],["STJ 104","STJ","Mercedes Sprinter","STJ-104",44,68,"🚑"],["DOT 88","DOT","Toyota Hilux","DOT-88",18,72,"🚧"],["NZP 9A-11","NZP","Kia Stinger","NZP-911",82,26,"🚓"],["FENZ 21","FENZ","Isuzu F-Series","FENZ-21",67,80,"🚒"],["STJ 221","STJ","Toyota HiAce","STJ-221",27,22,"🚑"]];
function go(id){document.querySelector(`[data-page="${id}"]`).click()}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById(b.dataset.page).classList.add("active");let t=b.textContent.trim().replace("2","");document.getElementById("title").textContent=t;document.getElementById("crumb").textContent=t.toUpperCase()});
function draw(filter="ALL",btn){if(btn){document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));btn.classList.add("active")}let map=document.getElementById("map");map.innerHTML="";units.filter(u=>filter==="ALL"||u[1]===filter).forEach(u=>{let b=document.createElement("button");b.className="blip "+u[1].toLowerCase();b.style.left=u[4]+"%";b.style.top=u[5]+"%";b.textContent=u[6];b.onclick=()=>alert(`${u[0]}\n${u[2]}\nRegistration: ${u[3]}\nDepartment: ${u[1]}`);map.appendChild(b)})}
document.getElementById("units").innerHTML=units.map(u=>`<div class="unit" onclick="alert('${u[0]}\n${u[2]}\nRegistration: ${u[3]}')"><span class="tag">● ACTIVE</span><b>${u[0]}</b><small>${u[1]} · ${u[2]} · ${u[3]}</small></div>`).join("");
function roles(){let d=document.getElementById("dept").value;document.getElementById("role").innerHTML=rolesData[d].map(x=>`<option>${x}</option>`).join("")}
const rolesData=roles; function changeRoles(){}
function openCase(){document.getElementById("modal").classList.remove("hidden")}function closeCase(){document.getElementById("modal").classList.add("hidden")}
function tick(){document.getElementById("time").textContent=new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"})}
draw();roles();tick();setInterval(tick,1000);document.getElementById("modal").onclick=e=>{if(e.target.id==="modal")closeCase()}